### ISSUE TITLE
Manca un problema sul correttore?

### ISSUE THREAD

**Issue by arn4** [olimpiadi-informatica/ois#17]
Volevo provare a scrivere la soluzione di grattacieli, ma non l'ho trovato sul correttore. Sono io stupido che non lo vedo o manca veramente?

P.S.: non so se era il caso di aprire un issue per una domanda così stupida. Se non dovevo rimuovetela pure.

**Comment by wil93** [comment]
Hai fatto bene a segnalarlo qui :+1: 

Per qualche motivo mancavano sia "grattacieli" che "calcolatrice", li ho aggiunti entrambi.
