### ISSUE TITLE
Trollface

### ISSUE THREAD

**Issue by Carlovan** [olimpiadi-informatica/ois#23]
Questa **Issue** non c'entra nulla con il _**Booklet**_, ma volevo condividere con voi la mia felicità nello scoprire la presenza, tra le _Emoji_ standardizzate, di una **TrollFace**!!!! :heart_eyes: :heart_eyes: 

:trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface:

**Comment by cip999** [comment]
-.-''
